### ISSUE TITLE
Output .graphql

### ISSUE THREAD

**Issue by Neitsch** [nodkz/webpack-plugin-graphql-schema-hot#1]
Hey, is there a reason there is no option to output a .graphql file? If not, I'll go ahead and make a PR.

**Comment by nodkz** [comment]
It does. In options it's called `output.txt`. Now it's no need in `.txt` extension.
```js
  txt: path.resolve(__dirname, '../build/schema.graphql.txt'),
```


Feel free to rename it to `graphql` and update README, thanks.
